#!/usr/bin/env python3
"""Regenerate the immutable 640 x 480 1bpp scene stored in XIP flash.

Run from any directory. --check exits nonzero if committed data is stale.
The GLCD font bytes remain subject to the license in VGA/font_glcd.c.
"""
import argparse
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "VGA" / "vga_background_data.h"


def generate():
    config = (ROOT / "board_config.h").read_text()
    def value(name):
        return int(re.search(r"^#define\s+" + name + r"\s+(\d+)\s*$", config, re.M)[1])
    assert value("BOARD_BALL_RADIUS") == value("BOARD_PEG_RADIUS") == 4
    width, height = 640, 480
    pixels = bytearray(width * height // 8)
    def pixel(x, y):
        assert 0 <= x < width and 0 <= y < height
        pixels[y * (width // 8) + x // 8] |= 1 << (x & 7)
    rows = value("BOARD_PEG_ROWS")
    center, top = value("BOARD_CENTER_X"), value("BOARD_TOP_Y")
    dx, dy = value("BOARD_PEG_HORIZONTAL_SPACING"), value("BOARD_PEG_VERTICAL_SPACING")
    for row in range(rows):
        for col in range(row + 1):
            x, y = center + (2 * col - row) * dx // 2, top + row * dy
            # Same midpoint-filled radius-four raster as mono_circle.h.
            for oy, mask in enumerate((0x38, 0xfe, 0xfe, 0x1ff, 0x1ff, 0x1ff, 0xfe, 0xfe, 0x38)):
                for ox in range(9):
                    if mask & (1 << ox): pixel(x + ox - 4, y + oy - 4)
    font_src = (ROOT / "VGA" / "font_glcd.c").read_text()
    font_src = font_src.split("font[] = {", 1)[1].split("};", 1)[0]
    font_src = re.sub(r"/\*.*?\*/|//[^\n]*", "", font_src, flags=re.S)
    font = bytes(int(s, 16) for s in re.findall(r"0x[0-9a-fA-F]+", font_src))
    labels = [(22, 10, "boids being animated: "),
              (22, 20, "Total fallen since reset: "),
              (22, 30, "Bounciness: "),
              (22, 40, "Time since boot: ")]
    for x, y, text in labels:
        for char in text:
            for col in range(5):
                for row in range(8):
                    if font[ord(char) * 5 + col] & (1 << row): pixel(x + col, y + row)
            x += 6
    metadata = """/* Generated by tools/generate_vga_background.py; do not edit.
 * Geometry comes from board_config.h; GLCD glyphs from font_glcd.c.
 * 38,400 bytes in .rodata / XIP flash; no third framebuffer in SRAM.
 */
#ifndef VGA_BACKGROUND_DATA_H
#define VGA_BACKGROUND_DATA_H
#include <stdint.h>
static const uint8_t vga_background_flash[38400] __attribute__((aligned(4))) = {
"""
    body = "".join("    " + ", ".join(f"0x{b:02x}" for b in pixels[i:i+16]) + ",\n"
                   for i in range(0, len(pixels), 16))
    return metadata + body + "};\n#endif\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != result:
            raise SystemExit("VGA background is stale: run tools/generate_vga_background.py")
        print("VGA flash background matches geometry and font")
    else:
        OUTPUT.write_text(result)
        print(f"Generated {OUTPUT.relative_to(ROOT)} (38400 bitmap bytes)")


if __name__ == "__main__":
    main()
